language: python

jobs:
  fast_finish: true
  include:

    - stage: Conan Latest - Macos
      language: generic
      os: osx
      osx_image: xcode10.3
      env: PYVER=py27 TOXENV=py27-conan-latest
    - language: generic
      os: osx
      osx_image: xcode10.3
      env: PYVER=py37 TOXENV=py37-conan-latest

install:
  - .ci/travis/install.sh

script:
  - .ci/travis/run.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
